extends:
  - airbnb-base
  - prettier
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'

parser: babel-eslint

env:
  node: true
  jest: true

plugins:
  - prettier
  - jest
  - babel

rules:
  no-console: 0
  prettier/prettier: 'error'
